# Generated by Django 3.2.5 on 2024-04-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('chembl_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True, verbose_name='chembl id')),
                ('e_id', models.CharField(default='-', max_length=20, verbose_name='e id')),
                ('target_id', models.CharField(default='-', max_length=25, verbose_name='chembl id')),
                ('target_uniport_id', models.CharField(default='-', max_length=50, verbose_name='target uid')),
                ('canonocal_smiles', models.CharField(default='-', max_length=200, verbose_name='smiles')),
                ('pchembl_value', models.FloatField(default=0.0, verbose_name='value')),
                ('standard_relation', models.CharField(default='=', max_length=5, verbose_name='standard relation')),
                ('standard_type', models.CharField(default='-', max_length=20, verbose_name='type')),
                ('standard_units', models.CharField(default='-', max_length=5, verbose_name='units')),
                ('standard_value', models.FloatField(default=0.0, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='disease id')),
                ('p_id', models.CharField(default='-', max_length=20, verbose_name='protein id')),
                ('s_id', models.CharField(default='-', max_length=50, verbose_name='site id')),
                ('tissue_cell', models.CharField(default='-', max_length=200, verbose_name='tissue/cell')),
                ('disease_ontology', models.CharField(default='-', max_length=200, verbose_name='disease ontology')),
                ('DO_id', models.CharField(default='-', max_length=20, verbose_name='disease id')),
                ('pubmed_id', models.CharField(default='-', max_length=50, verbose_name='pubmed id')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Inhibitor',
            fields=[
                ('i_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='i id')),
                ('e_id', models.CharField(default='-', max_length=20, verbose_name='e id')),
                ('name', models.CharField(default='-', max_length=50, verbose_name='name')),
                ('state', models.CharField(default='-', max_length=100, verbose_name='state')),
                ('drugbank_id', models.CharField(default='-', max_length=10, verbose_name='drug id')),
                ('disease', models.CharField(default='-', max_length=50, verbose_name='disease')),
                ('pubmed_id', models.CharField(default='-', max_length=50, verbose_name='pubmed')),
                ('description', models.TextField(default='-', verbose_name='descript')),
                ('inhibitor', models.CharField(default='-', max_length=30, verbose_name='inhibitor')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('uniport_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='uniport id')),
                ('reviewed', models.CharField(default='unreviewed', max_length=10, verbose_name='reviewed')),
                ('protein_name', models.CharField(default='-', max_length=50, verbose_name='name')),
                ('gene_symbol', models.CharField(default='-', max_length=50, verbose_name='gene')),
                ('entreze_id', models.CharField(default='-', max_length=20, verbose_name='entreze id')),
                ('ensembl_id', models.CharField(default='-', max_length=30, verbose_name='ensmbl id')),
                ('organism', models.CharField(default='-', max_length=100, verbose_name='organism')),
                ('organism_id', models.IntegerField(default=0, verbose_name='organism id')),
                ('sequence', models.TextField(default='-', verbose_name='sequence')),
                ('sid', models.CharField(default='-', max_length=20, verbose_name='site id')),
                ('site', models.CharField(default='-', max_length=20, verbose_name='site')),
                ('evidence', models.CharField(default='-', max_length=100, verbose_name='evidence')),
                ('evidence_source', models.CharField(default='-', max_length=50, verbose_name='evidence source')),
                ('database', models.CharField(default='-', max_length=20, verbose_name='database')),
                ('description', models.TextField(default='-', verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='PTase',
            fields=[
                ('eid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='e id')),
                ('ptase', models.CharField(default='-', max_length=15, verbose_name='PTase')),
                ('gene_symbol', models.CharField(default='-', max_length=100, verbose_name='gene symbol')),
                ('uniport_id', models.CharField(default='-', max_length=100, verbose_name='uniport id')),
                ('organism', models.CharField(default='-', max_length=100, verbose_name='organism')),
                ('organism_id', models.IntegerField(default=0, verbose_name='organism id')),
                ('enzyme_database', models.CharField(default='-', max_length=20, verbose_name='database')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('sid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='site id')),
                ('eid', models.CharField(default='-', max_length=10, verbose_name='e id')),
                ('ptase', models.CharField(default='-', max_length=15, verbose_name='PTase')),
                ('ptm', models.CharField(default='-', max_length=50, verbose_name='PTM')),
                ('donor', models.CharField(default='-', max_length=15, verbose_name='Donor')),
            ],
        ),
    ]
