# Generated by Django 3.2.5 on 2024-04-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0002_auto_20240407_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='organism_id',
            field=models.CharField(default='0', max_length=15, verbose_name='organism id'),
        ),
    ]
