# Generated by Django 3.2.5 on 2024-04-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0004_disease_protein_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhibitor',
            name='enzyme',
            field=models.CharField(default='-', max_length=100, verbose_name='enzyme'),
        ),
    ]
