# Generated by Django 3.2.5 on 2024-04-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0005_inhibitor_enzyme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='p_id',
        ),
    ]
