# Generated by Django 3.2.5 on 2024-04-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0006_remove_disease_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='family',
            field=models.CharField(default='-', max_length=100, verbose_name='family'),
        ),
    ]
