# Generated by Django 3.2.5 on 2024-04-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0007_protein_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='interpro_id',
            field=models.CharField(default='-', max_length=30, verbose_name='interpro id'),
        ),
    ]
