# Generated by Django 3.2.5 on 2024-04-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0008_protein_interpro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='length',
            field=models.IntegerField(default=0, verbose_name='seq len'),
        ),
    ]
