# Generated by Django 3.2.5 on 2024-05-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0009_protein_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhibitor',
            name='DO_id',
            field=models.CharField(default='-', max_length=20, verbose_name='disease id'),
        ),
    ]
