# Generated by Django 3.2.5 on 2024-05-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0010_inhibitor_do_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inhibitor',
            name='inhibitor',
        ),
    ]
