# Generated by Django 3.2.5 on 2024-05-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0011_remove_inhibitor_inhibitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhibitor',
            name='enzyme_type',
            field=models.CharField(default='-', max_length=100, verbose_name='enzyme type'),
        ),
    ]
